### ISSUE TITLE
Minor issue in perfdata line

### ISSUE THREAD

**Issue by yoshi314** [orthecreedence/check_elasticsearch#22]
```
OK - elasticsearch (MDMcluser) is running. status: green; timed_out: false; number_of_nodes: 3; number_of_data_nodes: 3; active_primary_shards: 13; active_shards: 29
100.0; relocating_shards: 0; initializing_shards: 0; delayed_unassigned_shards: 0; unassigned_shards: 0  | 'active_primary'=13 'active'=29
100.0 'relocating'=0 'init'=0 'delay_unass'=0 'unass'=0
```

the line break on active label cuts off all the other perfdata.

**Comment by yoshi314** [comment]
there are now 2 matching strings for active_shards in temporary file output, so this modification resolves the problem:



`    active_shards=`grep active_shards\" ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
`


The other match is active_shards_percent_as_number  , and can be added to the output.

**Comment by orthecreedence** [comment]
Any chance you can open a PR for this? I haven't actually used this script in a while. Most of the changes come from PRs. Thanks!

**Comment by yoshi314** [comment]
I'll try in a few days.
